


all:
	dot -Tpng fig2.5.after.dot > fig2.5.after.png
	dot -Tpng fig2.5.before.dot > fig2.5.before.png
	dot -Tpng fig2.7.after.dot > fig2.7.after.png
	dot -Tpng fig2.7.before.dot > fig2.7.before.png
	dot -Tpng fig2.8.after.dot > fig2.8.after.png
	dot -Tpng fig2.8.before.dot > fig2.8.before.png
	cp *.png ../org/img/
